### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by joschiv1977** [marcolivierarsenault/moonraker-home-assistant#161]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.loader
Source: custom_components/moonraker/sensor.py:25 
Integration: Moonraker (documentation, issues) 
First occurred: 16:05:35 (2 occurrences) 
Last logged: 16:13:34

Unexpected exception importing platform custom_components.moonraker.config_flow
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 744, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 761, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/moonraker/__init__.py", line 27, in <module>
    from .sensor import SENSORS
  File "/home/homeassistant/.homeassistant/custom_components/moonraker/sensor.py", line 22, in <module>
    class MoonrakerSensorDescription(SensorEntityDescription):
  File "/home/homeassistant/.homeassistant/custom_components/moonraker/sensor.py", line 25, in MoonrakerSensorDescription
    value_fn: Callable | None = None
TypeError: unsupported operand type(s) for |: 'ABCMeta' and 'NoneType'

**Comment by marcolivierarsenault** [comment]
What version of Home Assistant are you using?
