### ISSUE TITLE
Bug: Integration crashes if Moonraker is running but Klipper is not

### ISSUE THREAD

**Issue by heymoe** [marcolivierarsenault/moonraker-home-assistant#198]
## Version of the moonraker integration
0.10.0

## Describe your setup
Printer: Sovol SV06
Klipper Host Hardware: Raspberry Pi 4b
OS: PiOS / Debian Bullseye 64bit
Klipper Version: v0.11.0-275-g8ef0f7d7
Moonraker Version: v0.8.0-138-gfe120952
Mainsail Version: v2.7.1
KlipperScreen: v0.3.5-45-g75ee5c47

## Describe the bug
I configured a power device in Moonraker following the recommendations in the Mainsail docs ( https://docs.mainsail.xyz/overview/quicktips/printer-power-switch ). The way the power device is setup it has Klipper listed under bound_services which mean that when Moonraker turns off the power device it will stop the Klipper service and when it turns on the power device it will start the Klipper service.

I recently built a printer dashboard in Home Assistant making use of this integration and I added a power button to the dashboard using the Moonraker power device switch this integration creates. 

When the printer is on everything works as expected. All the sensors, macros, cameras, thumbnails, switches, etc.. this integration offers are available. If I turn the printer off using the Moonraker power device switch, the printer turns off as expect BUT the integration starts to crash and all the things become unavailable include the Moonraker power device switch so I can no longer turn the printer back on. 

Based on the below error message from Home Assistant and some testing I did, it seem that integration is crashing due to it not being able to pull information from Klipper via Moonraker when the Klipper service is not running. It looks like there needs to be some sort of check to see if Klipper is running and if not skip the queries related to Klipper while leaving the Moonraker provided things available such as the power device switch.

## Moonraker Logs
```
Logger: custom_components.moonraker
Source: custom_components/moonraker/__init__.py:107
Integration: Moonraker ([documentation](https://moonraker-home-assistant.readthedocs.io/en/latest/), [issues](https://github.com/marcolivierarsenault/moonraker-home-assistant/issues))
First occurred: 1:39:07 PM (9434 occurrences)
Last logged: 1:39:07 PM

Unexpected error fetching moonraker data: 'status'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 293, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/__init__.py", line 142, in _async_update_data
    data.update(await updater(self))
                ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/__init__.py", line 107, in _gcode_file_detail_updater
    data["status"]["print_stats"]["filename"]
    ~~~~^^^^^^^^^^
KeyError: 'status'
```

**Comment by marcolivierarsenault** [comment]
Can you please send a full log not only this part. 

Thank you

**Comment by heymoe** [comment]
For clarification, the log snippet I posted earlier was from Home Assistant and not Moonraker as labeled. 

Below are the relevant logs from Moonraker and Home Assistant matching entries timewise between the two.

### Moonraker Logs:

The printer powered off using the Moonraker power device (repeating every 30 sesc):
```
2023-09-11 11:58:46,113 [power.py:process_power_changed()] - Power Device printer: Performing stop action on bound service klipper
2023-09-11 11:58:46,182 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2023-09-11 11:58:46,669 [app.py:log_request()] - 503 GET /printer/objects/query?heater_bed&extruder&print_stats (10.66.100.23) [_API_KEY_USER_] 2.75ms
2023-09-11 11:58:58,159 [app.py:log_request()] - 404 GET /server/files/metadata?filename= (10.66.100.23) [_API_KEY_USER_] 7.08ms
2023-09-11 11:59:01,590 [app.py:log_request()] - 503 GET /printer/objects/query?heater_bed&extruder&print_stats (10.66.100.23) [_API_KEY_USER_] 2.20ms
2023-09-11 11:59:07,722 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.objects.query, Code: 503, Message: Klippy Host not connected
2023-09-11 11:59:07,730 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.info, Code: 503, Message: Klippy Host not connected
2023-09-11 11:59:07,739 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.objects.query, Code: 503, Message: Klippy Host not connected
2023-09-11 11:59:16,670 [app.py:log_request()] - 503 GET /printer/objects/query?heater_bed&extruder&print_stats (10.66.100.23) [_API_KEY_USER_] 7.23ms
2023-09-11 11:59:28,159 [app.py:log_request()] - 404 GET /server/files/metadata?filename= (10.66.100.23) [_API_KEY_USER_] 6.81ms
2023-09-11 11:59:31,593 [app.py:log_request()] - 503 GET /printer/objects/query?heater_bed&extruder&print_stats (10.66.100.23) [_API_KEY_USER_] 4.81ms
2023-09-11 11:59:37,722 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.objects.query, Code: 503, Message: Klippy Host not connected
2023-09-11 11:59:37,729 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.info, Code: 503, Message: Klippy Host not connected
2023-09-11 11:59:37,736 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.objects.query, Code: 503, Message: Klippy Host not connected

...

2023-09-11 14:56:16,598 [app.py:log_request()] - 503 GET /printer/objects/query?heater_bed&extruder&print_stats (x.x.x.x) [_API_KEY_USER_] 7.30ms
2023-09-11 14:56:28,539 [app.py:log_request()] - 404 GET /server/files/metadata?filename= (x.x.x.x) [_API_KEY_USER_] 6.50ms
2023-09-11 14:56:31,592 [app.py:log_request()] - 503 GET /printer/objects/query?heater_bed&extruder&print_stats (x.x.x.x) [_API_KEY_USER_] 3.35ms
2023-09-11 14:56:37,722 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.objects.query, Code: 503, Message: Klippy Host not connected
2023-09-11 14:56:37,729 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.info, Code: 503, Message: Klippy Host not connected
2023-09-11 14:56:37,738 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.objects.query, Code: 503, Message: Klippy Host not connected
2023-09-11 14:56:46,600 [app.py:log_request()] - 503 GET /printer/objects/query?heater_bed&extruder&print_stats (x.x.x.x) [_API_KEY_USER_] 6.80ms
2023-09-11 14:56:58,539 [app.py:log_request()] - 404 GET /server/files/metadata?filename= (x.x.x.x) [_API_KEY_USER_] 5.83ms
2023-09-11 14:57:01,598 [app.py:log_request()] - 503 GET /printer/objects/query?heater_bed&extruder&print_stats (x.x.x.x) [_API_KEY_USER_] 7.18ms
2023-09-11 14:57:07,724 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.objects.query, Code: 503, Message: Klippy Host not connected
2023-09-11 14:57:07,730 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.info, Code: 503, Message: Klippy Host not connected
2023-09-11 14:57:07,737 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.objects.query, Code: 503, Message: Klippy Host not connected
```


The printer powered back on using the Moonraker power device (nothing printing):
```
2023-09-11 14:57:12,471 [power.py:process_power_changed()] - Power Device printer: Performing start action on bound service klipper
2023-09-11 14:57:13,098 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2023-09-11 14:57:17,267 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2023-09-11 14:57:17,269 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2023-09-11 14:57:17,519 [job_state.py:_handle_started()] - Job state initialized: standby
2023-09-11 14:57:17,794 [klippy_connection.py:_check_ready()] - Klippy ready
2023-09-11 14:57:18,272 [data_store.py:_init_sensors()] - Configuring available sensors: ['temperature_sensor ezbrd_temp', 'temperature_sensor host_temp', 'heater_bed', 'temperature_sensor mcu_temp', 'extruder']
2023-09-11 14:57:28,540 [app.py:log_request()] - 404 GET /server/files/metadata?filename= (x.x.x.x) [_API_KEY_USER_] 5.30ms
2023-09-11 14:57:58,541 [app.py:log_request()] - 404 GET /server/files/metadata?filename= (x.x.x.x) [_API_KEY_USER_] 5.75ms
2023-09-11 14:58:28,541 [app.py:log_request()] - 404 GET /server/files/metadata?filename= (x.x.x.x) [_API_KEY_USER_] 5.67ms
```
The repeating errors stop


### Home Assistant Log

The printer is powered off using the Moonraker power device (repeating every 30 seconds):
```
2023-09-11 11:59:07.740 ERROR (MainThread) [custom_components.moonraker] Unexpected error fetching moonraker data: 'status'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 293, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/__init__.py", line 142, in _async_update_data
    data.update(await updater(self))
                ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/__init__.py", line 107, in _gcode_file_detail_updater
    data["status"]["print_stats"]["filename"]
    ~~~~^^^^^^^^^^
KeyError: 'status'

...

2023-09-11 14:57:07.738 ERROR (MainThread) [custom_components.moonraker] Unexpected error fetching moonraker data: 'status'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 293, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/__init__.py", line 142, in _async_update_data
    data.update(await updater(self))
                ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/__init__.py", line 107, in _gcode_file_detail_updater
    data["status"]["print_stats"]["filename"]
    ~~~~^^^^^^^^^^
KeyError: 'status'
```



Home Assistant Log: The printer is powered on using the Moonraker power device (nothing printing):
```
2023-09-11 14:57:38.101 INFO (MainThread) [custom_components.moonraker] Fetching moonraker data recovered
```

The crash errors stop.

If you need something more specific let me know.

**Comment by marcolivierarsenault** [comment]
@heymoe 

Are you comfortable with Git.

If so can you pull the branch `manage_klipper_down` and try to see if the bug is fixed.

**Comment by zimmra** [comment]
> @heymoe
> 
> Are you comfortable with Git.
> 
> If so can you pull the branch `manage_klipper_down` and try to see if the bug is fixed.

Initial result of this is good, I'll keep an eye on it to make sure the 'good behavior' continues in my system. 

I had same/similar issue as heymoe - I keep RPi running moonraker running 24/7 but manage my printer power with a smart switch. When printer was removed from power eventually integration would fail (or if printer was already powered off and home assistant restarted, it would never setup correctly)

Now with modified code it setup the moonraker integration even with printer powered off, so seems to have resolved - will try to report back in the coming day/days 

@marcolivierarsenault
