### ISSUE TITLE
New Install - no sensors, camera, thumbnail created

### ISSUE THREAD

**Issue by seanemclean** [marcolivierarsenault/moonraker-home-assistant#213]
## Version of the moonraker integration

0.10. Delete and Re-install already attempted

## Describe your setup

Voron 2.4, running mainsail/klipper

## Describe the bug

No sensors or cameras setup

## Moonraker Logs

**Sensor Setup Logs**

`Logger: homeassistant.components.sensor
Source: custom_components/moonraker/sensor.py:540
Integration: Sensor (documentation, issues)
First occurred: 6:36:35 PM (1 occurrences)
Last logged: 6:36:35 PM

Error while setting up moonraker platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/moonraker/sensor.py", line 327, in async_setup_entry
    await async_setup_basic_sensor(coordinator, entry, async_add_entities)
  File "/config/custom_components/moonraker/sensor.py", line 335, in async_setup_basic_sensor
    async_add_entities([MoonrakerSensor(coordinator, entry, desc) for desc in SENSORS])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/sensor.py", line 335, in <listcomp>
    async_add_entities([MoonrakerSensor(coordinator, entry, desc) for desc in SENSORS])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/sensor.py", line 473, in __init__
    self._attr_native_value = description.value_fn(self)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/sensor.py", line 275, in <lambda>
    value_fn=lambda sensor: calculate_current_layer(sensor.coordinator.data),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/sensor.py", line 540, in calculate_current_layer
    and "current_layer" in data["status"]["print_stats"]["info"]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
`

**Camera Logs**

Logger: homeassistant.components.camera
Source: custom_components/moonraker/camera.py:29
Integration: Camera (documentation, issues)
First occurred: 6:36:36 PM (1 occurrences)
Last logged: 6:36:36 PM

Error while setting up moonraker platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/moonraker/camera.py", line 29, in async_setup_entry
    for camera_id, camera in enumerate(cameras["webcams"]):
                                       ~~~~~~~^^^^^^^^^^^
KeyError: 'webcams'

**Comment by seanemclean** [comment]
Update, I had a print running when I first set it up. Print finished, nuked everything again, and now i have sensors but no cameras.

**Comment by marcolivierarsenault** [comment]
Hi, can you get the full debug logs:

Details here: https://moonraker-home-assistant.readthedocs.io/en/stable/support/logs.html#go-full-debug-log

**Comment by Samywamy10** [comment]
I have this same issue

**Comment by marcolivierarsenault** [comment]
please re-open with full log thanks
