### ISSUE TITLE
Preview image is periodically unavailable (Moonraker integration causes error in logs)

### ISSUE THREAD

**Issue by spikeygg** [marcolivierarsenault/moonraker-home-assistant#279]
## Describe your setup
Printer: Voron 2.4 w/ lotsa mods
Klipper: v0.12.0-111-g4f00f219
Moonraker: v0.8.0-311-g65a82719
Fluidd: v1.28.0
Mainsail: v2.10.0
ERCF v1.1 /w HappyHare: v2.4.2-83-gd450fe61

## Describe the bug

I noticed that when I look at my 3D printer page on Home Assistant a lot of the time, the preview image of the printed part isn't displayed... it comes up as the broken photo image. On a refresh of the page usually it will load. I didn't realize it but I think at the same time this is happening, there's an error generated in the Home Assistant system logs about bytes object not having a width attribute.

## Moonraker Logs

```
Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
First occurred: 8:05:50 PM (2 occurrences)
Last logged: 10:00:13 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 813, in get
    return await self.handle(request, camera)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 831, in handle
    image = await _async_get_image(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 191, in _async_get_image
    else await camera.async_camera_image(width=width, height=height)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/camera.py", line 151, in async_camera_image
    f"Size of thumbnail: {self._current_pic.width} x {self._current_pic.height}"
                          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'bytes' object has no attribute 'width'
```

**Comment by marcolivierarsenault** [comment]
What sclicer do you use

**Comment by spikeygg** [comment]
SuperSlicer and PrusaSlicer

**Comment by marcolivierarsenault** [comment]
yeah... We don't support these for now, eventually we should

**Comment by marcolivierarsenault** [comment]
can you share full debug logs please

https://moonraker-home-assistant.readthedocs.io/en/latest/support/logs.html#go-full-debug-log

**Comment by spikeygg** [comment]
> can you share full debug logs please

Sure thing. I started the debug logging, kicked off a print, and then navigated to the 3D Printer tab on my Home Assistant which tries to bring up the image. When the page comes up, it's a broken image picture for about 20 seconds. Then it refreshes to the correct image. In the debug log I think this is the most important part:

```
2024-03-31 09:16:53.555 DEBUG (MainThread) [custom_components.moonraker.camera] Trying to get thumbnail 
2024-03-31 09:16:53.555 DEBUG (MainThread) [custom_components.moonraker.camera] Thumbnail new_path: .thumbs/4xCoupler_Block_Base - 0s 3h41m-400x300.png
2024-03-31 09:16:53.555 DEBUG (MainThread) [custom_components.moonraker.camera] Fetching new thumbnail: http://voron.mynet/server/files/gcodes/.thumbs/4xCoupler_Block_Base - 0s 3h41m-400x300.png
2024-03-31 09:16:53.580 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 25, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 68, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 818, in get
    return await self.handle(request, camera)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 836, in handle
    image = await _async_get_image(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 191, in _async_get_image
    else await camera.async_camera_image(width=width, height=height)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/camera.py", line 173, in async_camera_image
    f"Size of thumbnail: {self._current_pic.width} x {self._current_pic.height}"
                          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'bytes' object has no attribute 'width'
2024-03-31 09:17:03.462 DEBUG (MainThread) [custom_components.moonraker.camera] Trying to get thumbnail 
2024-03-31 09:17:03.462 DEBUG (MainThread) [custom_components.moonraker.camera] Thumbnail new_path: .thumbs/4xCoupler_Block_Base - 0s 3h41m-400x300.png
2024-03-31 09:17:03.462 DEBUG (MainThread) [custom_components.moonraker.camera] no change in thumbnail, returning cached
```

Here's the whole log: 
[home-assistant_moonraker_2024-03-31T15-17-08.832Z.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/14816491/home-assistant_moonraker_2024-03-31T15-17-08.832Z.log)

Thank you!

**Comment by marcolivierarsenault** [comment]
ok issue occurs when there is a space in the file_name

**Comment by marcolivierarsenault** [comment]
can you try #308

**Comment by spikeygg** [comment]
@marcolivierarsenault what's the easiest way for me to evaluate this PR? I have the integration installed through HACS. I'm thinking:

1. clone repo locally
2. checkout PR branch
3. manually copy the file from local repo to HassIO system's config/custom_components/moonraker location
4. restart HA

... but maybe there's an easier way??

**Comment by marcolivierarsenault** [comment]
yeah, that is the best way I know (and it's pretty bad)

**Comment by spikeygg** [comment]
okay, I tried it out and it's a success. The image loads immediately and I don't see any errors in the logs.

**Comment by marcolivierarsenault** [comment]
Great, shipping the code
