### ISSUE TITLE
Setup failed for custom integration 'moonraker': Unable to import component: Exception importing custom_components.moonraker

### ISSUE THREAD

**Issue by IsioNisin** [marcolivierarsenault/moonraker-home-assistant#317]
## Version of the moonraker integration

1.2.0

## Describe your setup

Moonraker, Fluidd 

HA Core via Termux on Android

## Describe the bug

addon doesn't start

## Moonraker Logs

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/hass/lib/python3.11/site-packages/homeassistant/loader.py", line 921, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/data/com.termux/files/home/.homeassistant/custom_components/moonraker/__init__.py", line 30, in <module>
    from .sensor import SENSORS
  File "/data/data/com.termux/files/home/.homeassistant/custom_components/moonraker/sensor.py", line 451
    name=f"{split_obj[1].replace("_", " ")} Power".title(),
                                  ^
SyntaxError: f-string: unmatched '('

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/hass/lib/python3.11/site-packages/homeassistant/setup.py", line 296, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/hass/lib/python3.11/site-packages/homeassistant/loader.py", line 894, in async_get_component
    comp = self.get_component()
           ^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/hass/lib/python3.11/site-packages/homeassistant/loader.py", line 932, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.moonraker

**Comment by marcolivierarsenault** [comment]
do you have more logs, 

Can you include full debug logs please. 
https://moonraker-home-assistant.readthedocs.io/en/stable/support/logs.html#go-full-debug-log

**Comment by marcolivierarsenault** [comment]
@Vyolex graciously made a patch, can you try the latest code.

Download the `main` version. https://moonraker-home-assistant.readthedocs.io/en/stable/support/latest.html
