### ISSUE TITLE
HA beta 2024.08.0b0: TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by TheZoker** [marcolivierarsenault/moonraker-home-assistant#377]
## Version of the moonraker integration

1.2.2

## Describe the bug

Since the update to HA beta 2024.08.0b0 I get this error in the logs:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/moonraker/sensor.py", line 300, in async_setup_entry
    await async_setup_optional_sensors(coordinator, entry, async_add_entities)
  File "/config/custom_components/moonraker/sensor.py", line 595, in async_setup_optional_sensors
    async_add_entities([MoonrakerSensor(coordinator, entry, desc) for desc in sensors])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/sensor.py", line 773, in __init__
    self._attr_native_value = description.value_fn(self)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/sensor.py", line 418, in <lambda>
    sensor.coordinator.data["status"][sensor.status_key]["last_stats"][
TypeError: 'NoneType' object is not subscriptable
```

**Comment by marcolivierarsenault** [comment]
Thanks, I will keep an eye on this and test on my side

**Comment by marcolivierarsenault** [comment]
having the same issue with 2024.7.x

investigating

**Comment by marcolivierarsenault** [comment]
This is caused by #354 

Will revert

**Comment by marcolivierarsenault** [comment]
@TheZoker can you update your integration and test please (1.2.3)

**Comment by marcolivierarsenault** [comment]
Please reopen if needed
