### ISSUE TITLE
Printer power switch generating errors

### ISSUE THREAD

**Issue by potchin** [marcolivierarsenault/moonraker-home-assistant#403]
## Version of the moonraker integration
1.3.4

## Describe your setup

Klipper, Moonraker, Mainsail, Raspi.

Relay connected to the GPIO on the pi to control power to the printer board (SKR mini)

```
[power printer]
type: gpio
pin: gpio4
off_when_shutdown: True
initial_state: off
restart_klipper_when_powered: true
bound_services:
 klipper
 klipper-mcu
```

## Describe the bug

My power controls though moonraker work fine. When toggling the power switch entity through HA (`switch.am8_printer`) the UI shows an error `Failed to perform the action switch/turn off. state` but the power does toggle correctly. 

## HA Logs

```
2024-09-03 19:00:29.076 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/moonraker/sensor.py", line 796, in _handle_coordinator_update
    self._attr_native_value = self.entity_description.value_fn(self)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/sensor.py", line 46, in <lambda>
    value_fn=lambda sensor: sensor.coordinator.data["printer.info"]["state"],
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'state'
2024-09-03 19:00:35.086 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 813, in get
    return await self.handle(request, camera)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 831, in handle
    image = await _async_get_image(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 185, in _async_get_image
    else await camera.async_camera_image(width=width, height=height)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/camera.py", line 162, in async_camera_image
    self.coordinator.data["status"]["print_stats"]["state"]
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'status'
```

The corresponding error from `moonraker.log`...

```
2024-09-04 17:53:12,032 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.objects.query, Code: 503, Message: Klippy Host not connected
2024-09-04 17:53:12,039 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.info, Code: 503, Message: Klippy Host not connected
```

Klippy being disconnected is expected if the printer is off. Any suggestions?

**Comment by potchin** [comment]
Also noticed that the state gets out of sync. Eg, the state of the `switch` entity in HA is "on" but its actually powered off (which is correctly shown in mainsail)

**Comment by marcolivierarsenault** [comment]
Could you get a full copy of your log and reproduce the problems 


https://moonraker-home-assistant.readthedocs.io/en/stable/support/logs.html#get-a-copy-of-your-ha-logs

**Comment by garretthope98** [comment]
Also having this issue with a Wemo switch.
[home-assistant_moonraker_2024-12-16T22-08-28.895Z.log](https://github.com/user-attachments/files/18157619/home-assistant_moonraker_2024-12-16T22-08-28.895Z.log)

**Comment by philhagger** [comment]
I have this same issue with the latest updates

**Comment by marcolivierarsenault** [comment]
I just looked at the log (sorry for the delay)

Looks like we are getting a 503 back from moonraker... 

Looks like you cannot get any data back from moonraker as soon as the command is sent (and the switch is powered off) 

The only thing I can see is my configs for power switch don't include all the same options

```yml
[power printer]
type: tplink_smartplug
address: 192.168.1.2
restart_klipper_when_powered: True
```

I wonder if some of these option are causing your connection issues

**Comment by kvikindi** [comment]
I am having a very similar issue here, namely because of the `bound_services; klipper` bit, it seems.
My log is filled to the brim with Websocket error 500, to the point of shutting out access to moonraker itself, similar to #517 
Commenting out that particular configuration seems to soothe the log goblins a bit though...
